### ISSUE TITLE
RPGアツマール上でiOSでプレイした場合に画面がはみ出してしまう

### ISSUE THREAD

**Issue by rutan** [akashic-games/akashic-cli-export-html#54]
### 症状例
<img src="https://user-images.githubusercontent.com/1131422/47737400-31a63400-dcb4-11e8-9d16-dcc5705b6697.png" height="360">
（※公式さんのゲームですがわかりやすかったので…）

確認端末は iPhone 7（ iOS 12.0 ）です。

### 状況
iOS端末において、ゲームの解像度が端末の幅より大きい場合（iPhone8の場合 375px以上）、
resize処理の中で実行される `window.innerWidth` の値がゲーム解像度と同じになってしまい、
その後の中央寄せの計算で不適切な値が算出されているようです。

https://github.com/akashic-games/akashic-cli-export-html/blob/master/templates/template-export-html-v2/js/sandbox.js#L82-L102

※ ↑の `viewportSize.width` がゲーム解像度幅になってしまい、 `gameOffset .x` がずれています

**Comment by xnv** [comment]
akashic-cli-export-html@0.1.38 で修正しました。akashic-cli を再インストールいただくと直るはずです。(既存ゲームはもう一度 export していただく必要がありますが……)

(余談ながら) インストールされている akashic-cli-export-html のバージョンは以下のコマンドでご確認いただけます。
```
akashic export html -- -V
```

**Comment by rutan** [comment]
ありがとうございます！！

**Comment by xnv** [comment]
情報共有のため問題と対応方法を整理します:

### 現象

iOSでRPGアツマールを表示した時、画面が右にずれて表示されます。([このissue](https://github.com/akashic-games/akashic-cli-export-html/issues/54#issue-375609859)を参照のこと)
端末の解像度とゲームのサイズによっては、ずれすぎて何も表示されない場合もあります。

### 影響範囲と確認方法

akashic-cli-export-html@0.1.37 以前の全バージョンで再現します。すなわち、2018-11-06 以前にインストールされた akashic-cli が生成した全ての zip ファイルで問題を再現します。

以下のコマンドを実行して、 `0.1.38` 以上の値が表示されれば、この問題は発生しません。

```
akashic export html -- -V
```

### 対応方法

問題を再現する場合、修正には以下の手順が必要です:

1. akashic-cli を再インストールして、zipファイルを作り直す
2. RPGアツマールでゲームファイルの更新を行い、1で作ったzipファイルをアップロードする

akashic-cli は次のコマンドで再インストールできます。

```
npm install -g @akashic/akashic-cli
```

インストール後、以下を実行して、 `0.1.38` 以上であることを確認してください。

```
akashic export html -- -V
```

あとは [従前の文書](https://akashic-games.github.io/guide/export-atsumaru.html) に従い、 `akashic export html --output <zipFileName> --atsumaru` を実行して zip ファイルを生成してください。RPGアツマールのご自身のページから、ゲームのアップデートを行って zip ファイルを更新すれば問題を解消します。([参考](https://akashic-games.github.io/guide/export-atsumaru.html#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AE%E6%9B%B4%E6%96%B0))

なおこの問題はRPGアツマール上でのみ再現します。 「ニコニコ新市場に登録申請」を改めて行う必要はありません。
